### ISSUE TITLE
Impressed work

### ISSUE THREAD

**Issue by paulcx** [guillaume-chevalier/HAR-stacked-residual-bidir-LSTMs#10]
I'm wondering if such RNN network could be used to extract features from the time series data. If so, it will save a lot of work on feature engineering.

**Comment by guillaume-chevalier** [comment]
What you are wondering about is unsupervised learning, such as an autoregressive model. You might want to read this Reddit discussion and my answer to it:
https://www.reddit.com/r/MachineLearning/comments/6gt65z/d_does_it_make_sense_to_predictregress_time/
The question in that thread is about another GitHub repo of mine: https://github.com/guillaume-chevalier/seq2seq-signal-prediction
Note that it could be used for the purpose that you are talking about if you manage to extract the decoder's very first state values once the network is trained.

**Comment by paulcx** [comment]
@guillaume-chevalier Thanks. Can you provide any example of using the decoder's state value for feature extraction?

**Comment by guillaume-chevalier** [comment]
Interestingly, a new paper came out about that: https://arxiv.org/pdf/1706.08838.pdf
