### ISSUE TITLE
Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32

### ISSUE THREAD

**Issue by 2jungi** [guillaume-chevalier/HAR-stacked-residual-bidir-LSTMs#11]
Hi , your code helped me a lot.
I want to appreciate about it.

But when I try to run python config_dataset_HAR_6_classes.py, 
error occurs.

I attach the environment and log below.

Tensorflow version 1.1
OS : Ubuntu 16.04

-----------------------------------------------------------------------------------------------------------

test@test:~/HAR-stacked-residual-bidir-LSTMs$ python config_dataset_HAR_6_classes.py
learning_rate: 0.001
lambda_loss_amount: 0.005

Some useful info to get an insight on dataset's shape and normalisation:
features shape, labels shape, each features mean, each features standard deviation
((2947, 128, 9), (2947, 6), 0.099139921, 0.39567086)
the dataset is therefore properly normalised, as expected.
(128, ?, 9)
(?, 9)
Traceback (most recent call last):
  File "config_dataset_HAR_6_classes.py", line 195, in <module>
    run_with_config(EditedConfig, X_train, y_train, X_test, y_test)
  File "/home/jungi/HAR-stacked-residual-bidir-LSTMs/lstm_architecture.py", line 270, in run_with_config
    pred_y = LSTM_network(X, config, keep_prob_for_dropout)
  File "/home/jungi/HAR-stacked-residual-bidir-LSTMs/lstm_architecture.py", line 207, in LSTM_network
    hidden = tf.split(0, config.n_steps, feature_mat)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1198, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3306, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 514, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

**Comment by 2jungi** [comment]
I solved, It was problem since the version of Tensorflow

I revised some codes, then it works!

**Comment by guillaume-chevalier** [comment]
If you can post here the changes you needed to do, it may be useful to others if they encounter the same issue. However, I wouldn't have the time to review a full pull request for now.

**Comment by orchestor** [comment]
@2jungi can you post your modification so we can see the modification.

**Comment by arekusu04** [comment]
https://stackoverflow.com/questions/41842440/tensorflow-input-split-dim-of-split-op-has-type-float32-that-does-not-matc
