### ISSUE TITLE
Hello friends

### ISSUE THREAD

**Issue by gladuo** [guillaume-chevalier/HAR-stacked-residual-bidir-LSTMs#7]
Hello friend, I do the same experiments these days. The state-of-art model makes a good result of F1 score 91 %, I run his code and it is 91% but when I switched to use keras 2 with tf as backend and I could only got f1 score of 88% at most. What is your result using tf ?

**Comment by zhaoyu611** [comment]
Hello, gladuo. Cause the [DeepConvLSTM](https://github.com/sussexwearlab/DeepConvLSTM) is written by Theano, while we were coding in TensorFlow. I did not run him code in fact. In my opinion, the DeepConvLSTM has stored parameters in local, so I think there result should be nearby 91%. 
Maybe you can ask the author directly for more details.
